spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Production;encrypt=true;trustServerCertificate=true
    username: normal_user
    password: password04
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true

app:
  search:
    useFullTextSearch: true


#  INSERT INTO app_user (email, password, username, role)
#  VALUES ('admin1@wp.pl', '$2a$10$Ex02DfV0RrCd2ugBxnbEnOqnNy9tr.6pu0ZFVdbbSqRZHv9O1K0hu', 'admin1', 'ADMIN');
#  INSERT INTO shop(name) VALUES('olx');
#  INSERT INTO shop(name) VALUES('allegro');
#  INSERT INTO shop(name) VALUES('allegroLokalnie');
#  INSERT INTO offer_update_config(type, interval_time) VALUES('MANUAL', NULL);
#  INSERT INTO offer_update_config(type, interval_time) VALUES('AUTOMATIC', NULL);
#
#  INSERT INTO CATEGORY(name) VALUES('newsy');
#  INSERT INTO CATEGORY(name) VALUES('pomoc');
#  INSERT INTO CATEGORY(name) VALUES('zestawy');
#  INSERT INTO CATEGORY(name) VALUES('og√≥lne');


#  EXEC sp_add_job
#  @job_name = N'Backup_Production_FULL',
#
#  EXEC sp_add_jobstep
#  @job_name = N'Backup_Production_FULL',
#  @step_name = N'Backup Full',
#  @subsystem = N'TSQL',
#  @command = N'DECLARE @path NVARCHAR(256) = ''C:\Backups\Full\Production_FULL_'' + FORMAT(GETDATE(), ''yyyyMMdd_HHmmss'') + ''.bak'';
#  BACKUP DATABASE [Production] TO DISK = @path WITH COMPRESSION, INIT;',
#  @database_name = N'master';
#
#  EXEC sp_add_jobschedule
#  @job_name = N'Backup_Production_FULL',
#  @name = N'Co 3 dni',
#  @freq_type = 4,
#  @freq_interval = 3,
#  @active_start_time = 020000;
#  EXEC sp_add_jobserver @job_name = N'Backup_Production_FULL';
#
#
#
#  EXEC sp_add_job
#  @job_name = N'Backup_Production_DIFF',
#
#  EXEC sp_add_jobstep
#  @job_name = N'Backup_Production_DIFF',
#  @step_name = N'Backup Diff',
#  @subsystem = N'TSQL',
#  @command = N'DECLARE @path NVARCHAR(256) = ''C:\Backups\Differential\Production_DIFF_'' + FORMAT(GETDATE(), ''yyyyMMdd_HHmmss'') + ''.bak'';
#  BACKUP DATABASE [Production] TO DISK = @path WITH DIFFERENTIAL, COMPRESSION, INIT;',
#  @database_name = N'master';
#
#  EXEC sp_add_jobschedule
#  @job_name = N'Backup_Production_DIFF',
#  @name = N'Codziennie',
#  @freq_type = 4,
#  @freq_interval = 1,
#  @active_start_time = 010000;
#  EXEC sp_add_jobserver @job_name = N'Backup_Production_DIFF';
#
#
#  EXEC sp_add_job
#  @job_name = N'Backup_Production_LOG',
#  @description = N'Backup logu do katalogu Log co 4h.';
#
#  EXEC sp_add_jobstep
#  @job_name = N'Backup_Production_LOG',
#  @step_name = N'Backup Log',
#  @subsystem = N'TSQL',
#  @command = N'DECLARE @path NVARCHAR(256) = ''C:\Backups\Log\Production_LOG_'' + FORMAT(GETDATE(), ''yyyyMMdd_HHmmss'') + ''.trn'';
#  BACKUP LOG [Production] TO DISK = @path WITH COMPRESSION, INIT;',
#  @database_name = N'master';
#
#  EXEC sp_add_jobschedule
#  @job_name = N'Backup_Production_LOG',
#  @name = N'Co 4h',
#  @freq_type = 4,
#  @freq_interval = 1,
#  @freq_subday_type = 8,
#  @freq_subday_interval = 4;
#  EXEC sp_add_jobserver @job_name = N'Backup_Production_LOG';
#  GO