spring:
  datasource:
#    url: jdbc:h2:mem:devdb
    url: jdbc:h2:file:./dbTest/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
#  devtools:
#    restart:
#      enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console
#  sql:
#    init:
#      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
#    show-sql: true

    properties:
      hibernate:
#        type:
#          descriptor:
#            sql:
#              basic: true
        dialect: org.hibernate.dialect.H2Dialect
#logging.level.org.hibernate.SQL: DEBUG
#logging:
#  level:
#    org:
#      hibernate:
#        engine:
#          internal:
#            StatefulPersistenceContext=DEBUG:


#  insert into app_user ( email , password ,  username , role ) values ('admin1@wp.pl', '$2a$10$Ex02DfV0RrCd2ugBxnbEnOqnNy9tr.6pu0ZFVdbbSqRZHv9O1K0hu', 'admin1', 'ADMIN');
#  insert into shop(id,name) values('1','olx');
#  insert into shop(id,name) values('2','allegro');
#  insert into shop(id,name) values('3','allegroLokalnie');
#  insert into offer_update_config(id, type, interval_time) values('1','MANUAL',null);
#  insert into offer_update_config(id, type, interval_time) values('2','AUTOMATIC',null);